services:
  ollama:
    build:
      context: .
      dockerfile: Dockerfile.ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama-data:/root/.ollama
      - ./start_ollama.sh:/start_ollama.sh
    entrypoint: ["/bin/sh", "/start_ollama.sh"]
    environment:
      - OLLAMA_NO_TLS_VERIFY=1
    deploy:
      resources:
        limits:  # hardlimits
          cpus: "2.0"
          memory: 8g
        reservations:  # softlimits
          cpus: "1.0"
          memory: 6g

  api:
    build: ./ollama_server
    ports:
      - "8000:8000"
    depends_on:
      - ollama
    environment:
      - OLLAMA_HOST=http://ollama:11434
      - OLLAMA_NO_TLS_VERIFY=1 # disabling TLS
      # - PYTHONHTTPSVERIFY=0  # disabling TLS
      # - HF_HUB_DISABLE_SSL_VERIFICATION=1  # Excluding the HF SSL check.
    volumes:
      - ${HOME}/.cache/torch/sentence_transformers:/root/.cache/torch/sentence_transformers
    deploy:
      resources:
        limits:  # hardlimits
          cpus: "1.0"
          memory: 4g
        reservations:  # softlimits
          cpus: "0.5"
          memory: 2g

volumes:
  ollama-data:
