services:
  ollama:
    build:
      context: .
      dockerfile: Dockerfile.ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama-data:/root/.ollama
      - ./start_ollama.sh:/start_ollama.sh
    entrypoint: ["/bin/sh", "/start_ollama.sh"]
    deploy:
      resources:
        limits:  # hardlimits
          cpus: "8.0"
          memory: 12g
        reservations:  # softlimits
          cpus: "4.0"
          memory: 10g

  api:
    build: ./ollama_server
    ports:
      - "8000:8000"
    depends_on:
      - ollama
    environment:
      - OLLAMA_HOST=http://ollama:11434
      - OLLAMA_NO_TLS_VERIFY=1 # disabling TLS
      - PYTHONHTTPSVERIFY=0  # disabling TLS
    deploy:
      resources:
        limits:  # hardlimits
          cpus: "1.0"
          memory: 2g
        reservations:  # softlimits
          cpus: "0.5"
          memory: 1g

volumes:
  ollama-data:
